### PR TITLE
Fixed bugs related to yakuhai chun & kokushi ignoring tenhou + english names for yaku

### PR DESCRIPTION
**Pull request by Enerccio**

### CODE REVIEW

**Comment by Nihisil** [comment]
@Enerccio Thank you for the contribution! A good catch with kokushi and tenhou/chihou. Do you mind to add a unit test that will check that behavior?

Regarding English names. I think we can implement there another way. Something like https://docs.python.org/3/library/gettext.html

We can create a folder `locale` and put there `en.po` and `default.po`. Also, add an attribute to library settings with the locale name. It will allow to have a more flexible approach and later we can add more supported languages.

Let me know if you want to do that, or I can process on it.

**Comment by Enerccio** [comment]
I can look into making the unittest. For localization, personally, I would want both language variants (at least for my uses - I am displaying it as japanese/english in my game).

**Comment by Nihisil** [comment]
Got it. We can postpone localization since it is only two variants now. I will wait for unit test and after that PR will be merged :)

**Comment by Enerccio** [comment]
Done :)

**Comment by Nihisil** [comment]
Thank you for the contribution!

**Pull request merged**
