### PR TITLE
Optional rules: Renhou as yakuman, Daisharin, Daisuurin, Daichikurin; Yaku_id now supplied externally

### PR DESCRIPTION
**Pull request by Enerccio**
So I moved yaku_id from internal constant into externally supplied constant (in yaku_config) because adding new yaku was rather terrible :) 

If you merge this, I would want to work on refactoring optional rules and hand state (ie move stuff that are optional rule variants into separate class and have it as a parameter in hand_config so it cna be reused and it is cleaner)

### CODE REVIEW

**Comment by Nihisil** [comment]
Your changes look good :) I have one thing that concerns me. `yaku_id` was mapped to yaku ids from tenhou.net, so when we did hands validation we were able to match that our calculated yaku are identical to yaku from tenhou.

Maybe we can store them in the separate variable otherwise, we will be not able to do hands validation in the future.

**Comment by Enerccio** [comment]
if you can list them to me in order I could add them as constants in the yaku config, the point was that editing them across files was cumbersome.

**Comment by Nihisil** [comment]
What is point of editing them btw? For new yaku we can assign 100+ ids to avoid duplication with old ones.

**Comment by Enerccio** [comment]
well it is used in sorting the yaku, no?

**Comment by Nihisil** [comment]
It wasn't designed for that purpose, I have added them only to validation needs.

**Comment by Enerccio** [comment]
Ah okay, well maybe keep them for the ordering and just add `tenhou_id` with the old value?

**Comment by Nihisil** [comment]
Yep, this one looks good to me :)

**Comment by Enerccio** [comment]
added tenhou_id back, also refactored optional rules to separate class

**Comment by Nihisil** [comment]
Thank you for doing this!

**Comment by Enerccio** [comment]
haha I only started, now I will add all optional rules I know :)

**Comment by Nihisil** [comment]
@Enerccio I have sent you an invitation to project collaboration. I think it will be a bit easier to work without forks. But it is up to you how to process further.

**Pull request merged**
